#TODO: Update password only if password changed [05.02 17:25]
variables:
  passChanged: false


trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    options: '-DskipTests=true'
  
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/target/eschool.jar

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure1'
    appType: 'webAppLinux'
    WebAppName: $(WebAppName)
    deployToSlotOrASE: true
    ResourceGroupName: $(ResourceGroupName)
    SlotName: $(SlotName)
    packageForLinux: '$(System.DefaultWorkingDirectory)/target/eschool.jar'
    RuntimeStack: 'JAVA|8-jre8'
  env:
    MAPPED_ENV_DB_PASS: $(DatabasePassword)

- task: AzureAppServiceSettings@1
  condition: eq(variables.passChanged, 'true')
  inputs:
    azureSubscription: 'Azure1'
    appName: $(WebAppName)
    resourceGroupName: $(ResourceGroupName)
    appSettings: |
      [
         {
          "name": "DATASOURCE_PASSWORD",
          "value": $env:MAPPED_ENV_DB_PASS,
          "slotSetting": false
         }
      ]

