variables:
  prefix: crfinal
  location: eastus
  
  connection: Azure2
  SlotName: production
 
trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar'
    scannerMode: 'Other'
    extraProperties: sonar.projectKey=DevOps_Internship_DevOps_Internship
    
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    mavenOptions: '-Xmx3072m'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'sonar:sonar'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    options: '-Dmaven.test.skip'
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'
    
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/target/eschool.jar
    publishLocation: 'pipeline'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'AzureNew'
    appType: 'webAppLinux'
    WebAppName: 'app-$(prefix)-$(location)'
    deployToSlotOrASE: true
    ResourceGroupName: 'rg-$(prefix)-APP-$(location)'
    SlotName: '$(slotName)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/target/eschool.jar'
    RuntimeStack: 'JAVA|8-jre8'

